services:
  backend:
    build: ./backend
    image: ${DOCKER_USER}/docker-project-backend:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Параметры подключения к БД
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: momodb
      DB_USER: momouser
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - back_net
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      replicas: 2
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      interval: 10s
      retries: 5
    # Безопасность:
    read_only: true
    cap_drop:
      - ALL

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_URL: "/api" 
    image: ${DOCKER_USER}/docker-project-frontend:latest
    depends_on: 
      backend:
        condition: service_healthy         
    networks:
      - front_net
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost/momo-store/ || exit 1"]
      interval: 30s
      retries: 3
    profiles: ["development", "production"]

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: momouser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: momodb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "momouser"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - front_net
      - back_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro   # подключаем конфиг для прокси
    restart: unless-stopped
    profiles: ["production"]

# Описание томов и сетей
volumes:
  db_data:

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
